In [1]:
import torch
import pyTorchTemplate as ptt
import numpy as np

In [2]:
def f(x):
    return torch.exp(-(x[0]+2*x[1]+3*x[2]))

In [3]:
df,ddf,dddf,ddddf = ptt.get_derivatives_vector_input(4,f,[0.0,0.0,0.0],False)

In [4]:
df

array([-1., -2., -3.], dtype=float32)

In [5]:
ddf

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]], dtype=float32)

In [6]:
dddf

array([[[ -1.,  -2.,  -3.],
        [ -2.,  -4.,  -6.],
        [ -3.,  -6.,  -9.]],

       [[ -2.,  -4.,  -6.],
        [ -4.,  -8., -12.],
        [ -6., -12., -18.]],

       [[ -3.,  -6.,  -9.],
        [ -6., -12., -18.],
        [ -9., -18., -27.]]], dtype=float32)

In [9]:
ddddf[0,0,0,0],ddddf[0,0,2,2]

(1.0, 9.0)